BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>(); // Hashset is an unordered collection of unique elements (more performant than a List but doesnt allow duplicates)
    }

    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; } // generic interface - collection of method signatures bundled together.
                                                                     // ICollection required by Entity to outline methods for querying and changing data.
  }
  public enum CuisineName
  {
    Mexican,
    Italian,
    Szechuan,
    Cantonese,
    Thai,
    Indian,
    French,
    American,
    Mediterranean,
    Japanese,
    Ethiopian

  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")] // so we can utilize the "Delete" action still.
    public ActionResult DeleteConfirmed(int id) // different name because GET & POST have same signature (method name and parameters)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/search")]
    public ActionResult Search(string search)
    {
      List<Cuisine> model = _db.Cuisines.Include(cuisines => cuisines.Restaurants).ToList();

      Cuisine match = new Cuisine();

      if (!string.IsNullOrEmpty(search))
      {
       foreach(Cuisine cuisine in model)
       {
         if (cuisine.Name == search)
         {
           match = cuisine;
         }
       } 
      }
      List<Restaurant> matches = match.Restaurants.ToList();
      return View(matches);
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      thisRestaurant.Reviews = _db.Reviews.Where(review => review.RestaurantId == id).ToList();
      return View("Details", thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")] // so we can utilize the "Delete" action still.
    public ActionResult DeleteConfirmed(int id) // different name because GET & POST have same signature (method name and parameters)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h4>Add a new category of cuisine</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    <br>
    <input type="submit" value="Add new cuisine" class=btn />
}

BestRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine
<h2>Are you sure you want to delete this type of cuisine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

BestRestaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul>
  @if (@Model.Restaurants.Count == 0)
  {
    <p>no restaurants found</p>
  }

  @* @foreach (Restaurant restaurant in @Model.Restaurants)
  {
    <li>Name: @restaurant.Name | @Html.ActionLink("Edit Entry", "Edit", new { id = Model.CuisineId })</li>
    <li>Description: @restaurant.Description | @Html.ActionLink("Delete Entry", "Delete", new { id = Model.CuisineId })</li>
  } *@
</ul>

BestRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this category of cuisine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CuisineId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" class="btn" />
}

BestRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>; // gives access to neccessary list of items

<h1>Cuisines</h1>

<ul>
  @foreach(Cuisine cuisine in Model)
  {
      <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li> //property names of the object we pass in {id = item.ItemId} MUST match parameter names used by the target method (Details())
  }
</ul>

@if (@Model.Count == 0)
{
  <h3>No cuisines have been added yet!</h3>
} 
<br>
<p>@Html.ActionLink("Add new cuisine", "Create")</p>

BestRestaurants/Views/Cuisines/Search.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h2>Search Results:</h2>

@foreach(Restaurant rest in Model)
{
   <h3><li>@Html.ActionLink($"{rest.Name}", "Details", "Restaurants", new {id = rest.RestaurantId})</li></h3>
}